### PR TITLE
Optionally enable blocking profile in debug server

### PR DESCRIPTION
**Pull request by milkotodorov**

### CODE REVIEW

**Comment by ematpl** [comment]
Hi, @milkotodorov, thanks for the PR. It looks like this is a request to merge an existing branch on this repository that's quite old, though, and so it won't merge cleanly. Would you be interested in re-doing the commit on that branch to conform to the code patterns that are on the head of the master branch and resubmitting it?

Thanks,
Eric, CF Runtime Diego PM

**Comment by milkotodorov** [comment]
Hi Eric,

you mean to redo code changes about the blocking profiling?

Regards,
Milko

**Comment by ematpl** [comment]
@milkotodorov, yes, that's correct. The existing commit you requested to pull in won't merge cleanly.

Thanks,
Eric

**Comment by milkotodorov** [comment]
Which branch of the gorouter is compiling with the latest cf-debug-server. It is set currently to be compiled with 6e8c6102596e3fb6a17511f9f39fae64c89144a7.

**Comment by ematpl** [comment]
Hi, @milkotodorov, 

I believe the gorouter has been tracking the master branch of the cf-debug-server repository, as that's the only branch with the https://github.com/cloudfoundry-incubator/cf-debug-server/commit/6e8c6102596e3fb6a17511f9f39fae64c89144a7 commit in its ancestry. The gorouter [vendors its dependencies using `godep`](https://github.com/cloudfoundry/gorouter/blob/aa626b261ec99cf62495a486080597b091c2ab7b/Godeps/Godeps.json#L21-L24), though, so even after this change is incorporated you would have to request that the CF Routing team update the gorouter's version of this dependency. It seems like they should anyway, as the version they have vendored is over a year old and does not give them the ability to set their lager log level dynamically. (/cc @crhino @shalako)

Thanks,
Eric

**Comment by milkotodorov** [comment]
Hi @ematpl 

I've just submitted the requested change. However I didn't make the changes necessary on the gorouter side.

Regards,
Milko

**Comment by heyjcollins** [comment]
As this item has been open for quite a long time, I'm going to go ahead and close it.

**Pull request closed without merging**
